openapi: 3.0.0
info: 
  title: documentation for customer
  version: 1.0.0
  description: customer documentation for washington
paths: 
  /api/v1/customer:
    get:
      summary: this end point is to get all customers 
      tags: [customer]
      security: 
        - bearerAuth: []
      responses: 
        "200":
          description: All customers found
        "400":
          description: something went wrong

  /api/v1/customer/activeCustomer:
    get:
      summary: Get all active customers
      description: Active customers are customers with more than 19 orders.
      tags: [customer]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Active customers retrieved successfully
        "401":
          description: Token not found or invalid
        "500":
          description: Server error

  /api/v1/customer/inactiveCustomer:
    get:
      summary: Get all inactive customers
      description: inactive customers are customers with less than 20 orders.
      tags: [customer]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: inactive customers retrieved successfully
        "401":
          description: Token not found or invalid
        "500":
          description: Server error
