openapi: 3.0.0
info:
  title: password documentation
  version: 1.0.0
  description: password documentation for washington
paths:
  /api/v1/password/change:
    patch:
      summary: change password
      tags: [password]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
                - confirmNewPassword
              properties:
                currentPassword:
                  type: string
                  example: oldpassword123
                newPassword:
                  type: string
                  example: newpassword456
                confirmNewPassword:
                  type: string
                  example: newpassword456
      responses:
        "200":
          description: Password changed successfully
        "400":
          description: Password validation error
        "401":
          description: Token not found or invalid
        "404":
          description: Admin not found
